### ISSUE TITLE
Updating a plugin dependency unloads dependents but doesn't reload them

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/plugin-manager#12]
Probably low-priority (easy for me to workaround / low impact).

The situation is:

* I have a plugin I'm developing
* BetterChat is an optional dependency
* I updated BetterChat
* Plugins dependent on betterchat were unloaded before betterchat updated
* but only plugins installed via plugin manager were reloaded

I am not actually sure if any plugins were that were unloaded as being dependent on betterchat were deliberately reloaded since the other 2 (MXRandom and ManiaExchange) were also updated, so maybe they were just reloaded as part of their own update.

this screenshot shows:
* `cotd-hud-{dev,prelrelease,latest}` were running at 9:14:11
* unloaded as part of betterchat update
* not reloaded after
* solution: Had to manually go Developer > Load Plugin

![image](https://user-images.githubusercontent.com/1046448/174411825-8c2a3ce0-4439-447e-9195-21583a444dac.png)

**Comment by XertroV** [comment]
Cool.
BTW I noticed that reloading a dependency via ctrl+r *does* reload the dependent plugins (which is v useful for dev, particularly when importing stuff between two plugins you're actively working on).

**Comment by codecat** [comment]
Correct, because that is from within Openplanet itself which does index dependencies on reloading. The plugin manager "reloads" plugins in a different way:

1. Queue the plugin for unload
2. `yield()` since the unload is queued and takes 1 frame to complete
3. Load the plugin

In Openplanet itself, the process is more direct:

1. Unload the plugin and at the same time create a dependency index
2. Load the plugin and also reload all dependencies in the index

I'm working on making it so the plugin manager will work in the following way:

1. Build a sorted dependency index for the plugin we're updating
2. Queue the plugin for unload
3. `yield()` since the unload is queued and takes 1 frame to complete
4. Load all plugins in the dependency index built earlier (this also includes the updated plugin itself)

I might also have to look into optimizing this process so when multiple plugins are being updated, a singular index is built for all of those plugins rather than an index for each, followed by dependents reloading multiple times.
